### ISSUE TITLE
Change Login Button Title

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/threefold-forums#5]
3Bot Connect is now released under the brand ThreeFold Connect.
We need to change the loginbutton on the forum accordingly.

![Screenshot 2020-11-16 at 14 56 25](https://user-images.githubusercontent.com/29431263/99260626-eff57100-281b-11eb-9f4f-8cbd2152c864.png)

**Comment by Vilnite** [comment]
Please know that issue is duplicated: https://github.com/threefoldfoundation/home/issues/179

Close both when done!
